version: '3.9'

services:
  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: spasmilenkov
      POSTGRES_PASSWORD: strongPassword
      POSTGRES_DB: istoria
      POSTGRES_URL: postgresql://spasmilenkov:strongPassword@localhost:5434/istoria
      POSTGRES_PORT: 5434
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: