// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/21/2024, 11:38:20 AM
const configMerger = require("/home/spasmilenkov/repos/DND-Master/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/spasmilenkov/repos/DND-Master/apps/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/spasmilenkov/repos/DND-Master/apps/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/spasmilenkov/repos/DND-Master/apps/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/spasmilenkov/repos/DND-Master/apps/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/spasmilenkov/repos/DND-Master/apps/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/spasmilenkov/repos/DND-Master/apps/frontend/plugins/**/*.{js,ts,mjs}","/home/spasmilenkov/repos/DND-Master/apps/frontend/composables/**/*.{js,ts,mjs}","/home/spasmilenkov/repos/DND-Master/apps/frontend/utils/**/*.{js,ts,mjs}","/home/spasmilenkov/repos/DND-Master/apps/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/spasmilenkov/repos/DND-Master/apps/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/spasmilenkov/repos/DND-Master/apps/frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
