# .github/workflows/ci-pipeline.yml
name: CI Pipeline

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  pr-check:
    uses: ./.github/workflows/pr-check.yml

  lint-and-test:
    needs: pr-check
    if: ${{ needs.pr-check.outputs.pr_invalid == 'false' }}
    uses: ./.github/workflows/lint-and-test.yml

  build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .turbo
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
