name: Enforce PR Policy

on:
  pull_request:
    branches: [ "main" ]

jobs:
  enforce-pr-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from dev
        id: check_branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" != "dev" ]]; then
            echo "Invalid PR source branch" 
            echo "pr_invalid=true" >> $GITHUB_ENV
          else
            echo "pr_invalid=false" >> $GITHUB_ENV
          fi

      - name: Comment and close PR
        if: env.pr_invalid == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            await github.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: "This pull request is being closed because pull requests to the main branch must come from the dev branch."
            });
            await github.pulls.update({
              ...context.repo,
              pull_number: prNumber,
              state: 'closed'
            });
