# .github/workflows/pr-check.yml
name: PR Check

on:
  workflow_call:

jobs:
  pr-check:
    runs-on: ubuntu-latest
    outputs:
      pr_invalid: ${{ steps.set-output.outputs.pr_invalid }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify pull request source branch
        id: check_branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" != "dev" ]]; then
            echo "pr_invalid=true" >> $GITHUB_ENV
          else
            echo "pr_invalid=false" >> $GITHUB_ENV
          fi

      - name: Set output
        id: set-output
        run: echo "::set-output name=pr_invalid::${{ env.pr_invalid }}"

      - name: Comment and close invalid PR
        if: env.pr_invalid == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            await github.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: "This pull request is being closed because pull requests to the main branch must come from the dev branch."
            });
            await github.pulls.update({
              ...context.repo,
              pull_number: prNumber,
              state: 'closed'
            });
